# CloudWhisper Configuration Example
# Copy this file to ~/.cloudwhisper/config.yaml and customize

# AWS Configuration
aws:
  default_region: us-east-1
  profile: default  # AWS profile to use

# OpenAI Configuration (for Terraform generation)
openai:
  api_key: your_openai_api_key_here
  model: gpt-4
  temperature: 0.1
  max_tokens: 2000

# Cost Analysis Settings
cost_analysis:
  default_days: 30
  default_granularity: DAILY
  currency: USD

# Optimization Settings
optimization:
  cpu_threshold_low: 10    # CPU % below which instances are considered underutilized
  cpu_threshold_high: 80   # CPU % above which instances may need upsizing
  idle_days_threshold: 7   # Days to look back for idle resource detection

# Terraform Settings
terraform:
  default_provider_version: "~> 5.0"
  include_tags: true
  default_tags:
    Environment: dev
    ManagedBy: CloudWhisper
    Project: infrastructure

# Output Settings
output:
  format: table  # table, json, yaml
  show_colors: true
  max_rows: 50
